apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rabbit/deployment.yaml
  - rabbit/service.yaml

  - datagen/deployment.yaml
  - datagen/service.yaml

  - processor/deployment.yaml

  - distributor/deployment.yaml

  - statistics/deployment.yaml


configMapGenerator:
  - name: queue.dsn
    envs:
      - ./configs/queue.env
  - name: distributor-conf
    files:
      - ./configs/distributor.json

  - name: processor-conf
    files:
      - ./configs/processor.json
