apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\bin\kompose.exe convert -o specs/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: datagen
  name: datagen
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 80
  selector:
    io.kompose.service: datagen
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\bin\kompose.exe convert -o specs/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit
  name: rabbit
spec:
  ports:
  - name: "8001"
    port: 8001
    targetPort: 15672
  selector:
    io.kompose.service: rabbit
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bin\kompose.exe convert -o specs/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: datagen
  name: datagen
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: datagen
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bin\kompose.exe convert -o specs/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: datagen
    spec:
      containers:
      - env:
        - name: QUEUE_URL
          value: rabbit:5672
        image: datagen
        imagePullPolicy: ""
        name: datagen
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bin\kompose.exe convert -o specs/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: distributor
  name: distributor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: distributor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bin\kompose.exe convert -o specs/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: distributor
    spec:
      containers:
      - env:
        - name: QUEUE_URL
          value: rabbit:5672
        image: distributor
        imagePullPolicy: ""
        name: distributor
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bin\kompose.exe convert -o specs/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: processor
  name: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: processor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bin\kompose.exe convert -o specs/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: processor
    spec:
      containers:
      - env:
        - name: QUEUE_URL
          value: rabbit:5672
        image: processor
        imagePullPolicy: ""
        name: processor
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bin\kompose.exe convert -o specs/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit
  name: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbit
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bin\kompose.exe convert -o specs/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: rabbit
    spec:
      containers:
      - image: rabbitmq:management
        imagePullPolicy: ""
        name: rabbit
        ports:
        - containerPort: 15672
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bin\kompose.exe convert -o specs/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: statistics
  name: statistics
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: statistics
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bin\kompose.exe convert -o specs/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: statistics
    spec:
      containers:
      - env:
        - name: QUEUE_URL
          value: rabbit:5672
        image: statistics
        imagePullPolicy: ""
        name: statistics
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
