[tool.poetry]
name = "processor"
version = "0.1.0"
description = ""
authors = ["intey <ziexe0@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
rabbitmq = "^0.2.0"
pika = "^1.1.0"
tqdm = "^4.48.0"
aiokafka = "^0.7.0"
aiohttp = "^3.7.4"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]
mypy = "^0.782"
pytest = "^5.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
