apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bin\kompose.exe convert -o specs/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: statistics
  name: statistics
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: statistics
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bin\kompose.exe convert -o specs/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: statistics
    spec:
      containers:
      - image: statistics
        envFrom:
        - configMapRef: 
            name: queue.dsn
        imagePullPolicy: IfNotPresent
        name: statistics
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
