apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases: 
  - ../base/

images:
  - name: datagen
    newName: eventbasedsystem/datagen
  - name: processor
    newName: eventbasedsystem/processor
  - name: statistics
    newName: eventbasedsystem/statistics
  - name: distributor
    newName: eventbasedsystem/distributor
  - name: rabbitmq
    newName: rabbitmq
    newTag: management-alpine

