apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\bin\kompose.exe convert -o specs/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: datagen
  name: datagen
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: datagen
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\bin\kompose.exe convert -o specs/
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: datagen
    spec:
      containers:
      - env:
        - name: QUEUE_URL
          value: rabbit:5672
        image: datagen
        imagePullPolicy: Never
        name: datagen
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
