apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\bin\kompose.exe convert -o specs/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: datagen
  name: datagen
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 80
  selector:
    io.kompose.service: datagen
status:
  loadBalancer: {}
